log:
  level: DEBUG

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  mqtts:
    address: ":8883"
  dcc:
    address: ":2560"
  rocrail:
    address: ":8051"

providers:
  docker:
    endpoint: "unix:///run/balena-engine.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_conf.yaml"
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: "${CF_API_EMAIL}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers: ["1.1.1.1:53", "8.8.8.8:53"]
